/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a3ac53b5-7112-4c58-bbd1-90eec677b9dd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_W4NJmeanV",
    "aws_user_pools_web_client_id": "6kbl3ciqvpd6s64hgqf1vcoq00",
    "oauth": {
        "domain": "hashcloud3fd491ec-3fd491ec-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "htt://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
